version: '3.8'

services:
  blockscout:
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    restart: always
    container_name: 'halo-browser'
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    ports:
      - 4000:4000

